app:
  env:
    server.port: 8080
    spring.datasource.username: devopsuser
    spring.datasource.password: RGomWH4BLdSb6rwGPrsiuPwaNJkEFELZ
    spring.datasource.url: "jdbc:postgresql://dpg-d0oa61juibrs73a8nne0-a.oregon-postgres.render.com:5432/devopsdb_n794"

service:
  workdir: /home/azureuser/backend/
  execstart: "/home/azureuser/backend/crowdfunding/target/crowdfunding-0.0.1-SNAPSHOT.jar"