apiVersion: v1
kind: Service
metadata:
  labels:
    app: js
  name: js-svc
spec:
  ports:
    - port: 7000
      protocol: TCP
      targetPort: 80
      name: js
  selector:
    app: js
  type: ClusterIP
