ansible_python_interpreter: /usr/bin/python3

ansible_host: "{{ lookup('env', 'ANSIBLE_HOST') }}"
ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY') }}"