--- 
- name: Upload SSH key and setup known_hosts
  hosts: all
  become: true
  
  vars:
    ssh_dir: /var/lib/jenkins/.ssh
    ssh_private_key: "{{ lookup('env', 'HOME') + '/.ssh/id_devops' }}"
    ssh_key_dest: "{{ ssh_dir }}/id_devops"

  tasks:
    - name: Ensure ssh directory exists
      file:
        path: "{{ ssh_dir }}"
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0700'

    - name: Upload ssh private key from WSL to remote
      copy:
        src: "{{ ssh_private_key }}"
        dest: "{{ ssh_key_dest }}"
        owner: jenkins
        group: jenkins
        mode: '0600'
      no_log: true

    - name: Add remote host to known_hosts 
      shell: ssh-keyscan -H {{ ansible_host }} >> {{ ssh_dir }}/known_hosts
      args:
        creates: "{{ ssh_dir }}/known_hosts"
  
    - name: Set permissions for known_hosts
      file:
        path: "{{ ssh_dir }}/known_hosts"
        owner: jenkins
        group: jenkins
        mode: '0644'
  