---
- hosts: all

  tasks:
    - name: Install basic packages
      apt:
        name: "{{item}}"
        state: present
        update_cache: true
      loop:
        - software-properties-common
        - curl
        - apt-transport-https
        - ca-certificates
      become: yes

    - name: get key
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
      #ignore_errors: yes
      become: yes

    - name: Add docker ppa
      apt_repository:
      #todo: check compatibility with other ubuntu versions
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes
      become: yes

    - name: install docker
      apt:
        name: "{{item}}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-compose
      become: yes

    - name: start docker service
      service:
        name: docker
        state: started
        enabled: true
      become: yes

    - name: adding existing user to group docker
      user:
        name: "{{  ansible_user_id }}"
        groups: docker
        append: yes
      become: yes

    - name: Copy docker-compose file
      copy:
        src: "{{ playbook_dir }}/../../docker/docker-compose.yaml"
        dest: /home/{{ ansible_user_id }}/docker-compose.yaml
        owner: "{{ ansible_user_id }}"
        group: docker
        mode: '0644'
      become: yes

    - name: Run docker-compose 
      command: docker-compose up -d
      args:
        chdir: /home/{{ ansible_user_id }}
      become: yes
