---
- name: Deploy Node.js Application
  hosts: all
  become: true

  tasks:
    - name: Update apt cache and install curl
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Add NodeSource repository for Node.js 18.x
      shell: curl -sL https://deb.nodesource.com/setup_18.x | bash -
      args:
        executable: /bin/bash

    - name: Install Node.js (includes npm)
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Verify Node.js version
      command: node -v

    - name: Verify npm version
      command: npm -v

    - name: Synchronize frontend folder
      synchronize:
        src: "{{ playbook_dir }}/../../App/frontend/"
        dest: "{{ frontend_dir }}/"
        recursive: yes
    
    - name: Allow others to execute /home/azureuser so nginx can access frontend
      file:
        path: /home/azureuser
        mode: '0751'
        state: directory

    - name: Install npm dependencies
      command: npm install
      args:
        chdir: "{{ frontend_dir }}"

    - name: Run serverInit.js with PM2
      shell: |
        npm install -g pm2
        pm2 delete all || true
        pm2 start serverInit.js --name frontend-server
        pm2 save
      args:
        chdir: "{{ frontend_dir }}"

    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy NGINX config for Node.js app
      template:
        src: ./../reverseproxy/nginx.node.j2
        dest: "{{ nginx_sites_available_path }}/{{ nginx_node_conf_filename }}"
      become: true

    - name: Enable Node.js site in NGINX
      file:
        src: "{{ nginx_sites_available_path }}/{{ nginx_node_conf_filename }}"
        dest: "{{ nginx_sites_enabled_path }}/{{ nginx_node_conf_filename }}"
        state: link
      become: true
      notify: restart nginx

    - name: Disable default NGINX site
      file:
        path: "{{ nginx_sites_enabled_path }}/default"
        state: absent
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
