---
- hosts: all
          
  pre_tasks:
    - name: Install Java
      apt:
          name: openjdk-21-jdk
          state: present
          update_cache: yes
      become: true

  tasks:
      - name: "debug appdir"
        ansible.builtin.debug:
          msg: "appdir {{ansible_user_dir}}"

      - name: Remove backend directory if exists
        file:
          path: "{{ backend_dir }}"
          state: absent
        become: true

      - name: "Clone the Spring repository"
        git:
            repo: "https://github.com/NikosZapantis/DS_crowdfunding.git"
            dest: "{{ appdir }}"
            version: "{{ branch }}"
            force: yes
      
      - name: Populate application.properties
        template:
          src: ./../templates/application.properties.j2
          dest: "{{ appdir }}/crowdfunding/src/main/resources/application.properties"
        become: true

      - name: Set execute permission for mvnw
        file:
          path: "{{ appdir }}/crowdfunding/mvnw"
          mode: '0755'
        become: true
      
      - name: "Build spring project"
        block:

        - name: "Build the Spring application"
          command: "./mvnw package -Dmaven.test.skip "
          args:
              chdir: "{{ appdir }}/crowdfunding"

        rescue:

        - name: Fetch the SHA-512 checksum for Maven 3.9.9
          get_url:
            url: https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip.sha512
            dest: /tmp/maven_sha512.txt
            validate_certs: yes
            force: yes

        - name: Read the SHA-512 checksum from the file
          command: cat /tmp/maven_sha512.txt
          register: sha512_checksum

        - name: Replace the distributionSha512Sum line in maven-wrapper.properties
          replace:
            path: "{{ appdir }}/crowdfunding/.mvn/wrapper/maven-wrapper.properties"
            regexp: '^distributionSha'
            replace: "distributionSha512Sum={{ sha512_checksum.stdout }}"
        
        - name: Clean up the temporary file
          file:
            path: /tmp/maven_sha512.txt
            state: absent
          when: sha512_checksum is defined
        
        always:
          - name: "Build the Spring application"
            command: "./mvnw package -Dmaven.test.skip "
            args:
                chdir: "{{ appdir }}/crowdfunding"


      - name: copy spring service file
        template:
          src: ./../files/spring.service.j2
          dest: "{{ spring_service_file }}"
        become: true
        become_user: root
        notify: restart spring

      - name: reload spring service
        service:
          name: spring
          state: restarted
        become: true

      - name: ensure spring service started
        service:
          name: spring
          state: started
          enabled: yes
        become: true

  handlers:
  - name: restart spring
    service:
      name: spring
      state: restarted
    become: true

  - name: restart nginx
    service:
      name: nginx
      state: restarted
    become: true
