---
  - name: install nginx server
    hosts: all
    become: yes
    become_user: root

    tasks:
      - name: install nginx package
        become: yes
        become_user: root
        apt:
          name: nginx
          state: present
          update_cache: yes
      