apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: default
  labels:
    app: spring
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 1
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: ghcr.io/tsadimas/ds-lab-2024:0f3ade0-1 #TODO: Update with our image
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8080
            failureThreshold: 20
            periodSeconds: 10
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
            failureThreshold: 10
            periodSeconds: 10
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/dsdb #TODO: change to our db link
            - name: SPRING_DATASOURCE_USERNAME
              value: dbuser #TODO: Change to the real username
            - name: SPRING_DATASOURCE_PASSWORD
              value: pass #TODO: our db password
          ports:
          - containerPort: 8080
            name: spring
      imagePullSecrets:
      - name: registry-credentials
