apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
spec:
  rules:
    - host: spring.example.com #TODO: Change to the real domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring
                port:
                  number: 80
